name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Flutter (pin to your version)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1' # Adjust to your Flutter version
          channel: 'stable'
          architecture: x64

      # Get packages
      - run: flutter pub get

      # Update CocoaPods repo
      - run: pod repo update
        working-directory: ios

      # Install Pods (important for CI)
      - run: pod install --repo-update
        working-directory: ios

      # Build IPA (no codesign)
      - run: |
          flutter build ipa --release --no-codesign
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Runner.ipa Payload

      # Upload IPA as artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa

      # (Optional) Publish to GitHub Releases
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/ipa/*.ipa
          tag: v1.0
          overwrite: true
          body: "iOS unsigned IPA export"
